baseurl = "https://www.eclipse.org/"
DefaultContentLanguage = "en"
title = "The Community for Open Innovation and Collaboration"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The Eclipse Foundation provides our global community of individuals and organizations with a mature, scalable, and business-friendly environment for open source software collaboration and innovation."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse", "project", "plug-ins", "plugins", "java", "ide", "swt", "refactoring", "free java ide", "tools", "platform", "open source", "development environment", "development", "ide"]
  news_count = 3
  gcse = "011805775785170369411:p3ec0igo0qq"
  header_wrapper_class = "header-wrapper header-default-bg-img featured-jumbotron-bottom-shape"
  call_for_action_text = "Download"
  call_for_action_url = "//eclipse.org/download/"
  call_for_action_icon = "fa-download"
# sidebar_layout = "default"
# featured_content_publish_target = "eclipse_org"
#  js = ""
#  styles = ""
#  logo = ""
#  favicon = ""
#  share_img = ""
#  logo_width = ""
#  header_left_classes = ""
#  main_menu_wrapper_classes = ""
#  projects_working_group = ""

  
[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "ECDTools"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 1
    
[[menu.main]]
    name = "Working Groups"
    url = "/org/workinggroups"
    weight = 2

[[menu.main]]
    name = "Members"
    url = "/membership"
    weight = 3
    
[[menu.sidebar]]
  name = "Documentation"
  url = "/home"
  weight = 1
  identifier = "home"
  
[[menu.sidebar]]
  parent ="home"
  name = "hugo-solstice-theme"
  url = "https://eclipsefdn-hugo-solstice-theme.netlify.app/"
  weight = 1
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"
  
[[menu.sidebar]]
  parent ="home"
  name = "Solstice"
  url = "https://www.eclipse.org/eclipse.org-common/themes/solstice/docs/"
  weight = 2
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "Hugo"
  url = "https://gohugo.io/documentation/"
  weight = 3
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"